# Generated by Django 2.2.5 on 2019-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_many_relationship_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='bags_purchased',
            field=models.ManyToManyField(to='many_many_relationship_django_app.bags'),
        ),
    ]
